import type { QuestionData, NavigatorState } from './types';

export const questions: QuestionData[] = [
  {
    number: 1,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 2.0,
    prompt: [
      { value: 'In the Raft consensus algorithm, when a follower node experiences an election timeout without receiving any ' },
      { value: 'AppendEntries RPC', code: true },
      { value: ' or ' },
      { value: 'RequestVote RPC', code: true },
      { value: ' from a leader or candidate, what immediate state transition and sequence of actions does it perform?' },
    ],
    specTitle: 'FORMAL STATE SPECIFICATION (§5.2 LEADER ELECTION)',
    specLink: 'RFC Consensus Model',
    specLines: [
      '[State: Follower]',
      '  |',
      '  (election timeout elapses without heartbeat)',
      '  v',
      '[State: Candidate]',
      '  - currentTerm += 1',
      '  - votedFor = self.nodeId',
      '  - broadcast RequestVote(term=currentTerm, candidateId=self.nodeId, ...)',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'It enters the Candidate state, increments its ' },
          { value: 'currentTerm', code: true },
          { value: ', votes for itself, and broadcasts ' },
          { value: 'RequestVote', code: true },
          { value: ' RPCs to all other nodes in the cluster.' },
        ],
      },
      {
        id: 'B',
        text: [
          { value: 'It immediately transitions to Leader state and begins transmitting empty ' },
          { value: 'AppendEntries', code: true },
          { value: ' heartbeats to re-establish network authority.' },
        ],
      },
      {
        id: 'C',
        text: [
          { value: 'It resets its election timer, remains in Follower state, and logs a split-vote warning to cluster logs without notifying peers.' },
        ],
      },
      {
        id: 'D',
        text: [
          { value: 'It contacts the configuration coordination service (such as Apache ' },
          { value: 'ZooKeeper', code: true },
          { value: ') to verify leader lease validity before incrementing its internal term counter.' },
        ],
      },
    ],
    selectedOptionId: 'A',
    citation:
      'Ongaro, D., & Ousterhout, J. (2014). "In Search of an Understandable Consensus Algorithm." USENIX ATC \'14. Section 5.2.',
  },
  {
    number: 2,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 2.0,
    prompt: [
      { value: 'According to the CAP theorem, a distributed data store can simultaneously guarantee at most two of the following properties during a ' },
      { value: 'network partition', code: true },
      { value: ': Consistency, Availability, and Partition Tolerance. Which statement below correctly characterizes this trade-off?' },
    ],
    specTitle: 'FORMAL STATEMENT (BREWER, 2000 / GILBERT & LYNCH, 2002)',
    specLink: 'CAP Theorem Proof Sketch',
    specLines: [
      '[Assume: Partition P occurs between node A and node B]',
      '  |',
      '  IF system chooses Consistency',
      '    -> requests may be blocked or rejected until partition heals (sacrifice A)',
      '  IF system chooses Availability',
      '    -> requests are served with possibly stale data (sacrifice C)',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'Since ' },
          { value: 'P', code: true },
          { value: ' (partition tolerance) is effectively mandatory for any distributed system, a real system must choose between prioritizing ' },
          { value: 'C', code: true },
          { value: ' or ' },
          { value: 'A', code: true },
          { value: ' when a partition actually occurs.' },
        ],
      },
      {
        id: 'B',
        text: [
          { value: 'A well-engineered system can guarantee all three properties simultaneously as long as it uses ' },
          { value: 'TCP', code: true },
          { value: ' for all inter-node communication.' },
        ],
      },
      {
        id: 'C',
        text: [{ value: 'Consistency and availability are unrelated to network partitions and only depend on disk write latency.' }],
      },
      {
        id: 'D',
        text: [{ value: 'Partition tolerance is optional in modern data centers because physical network failures no longer occur.' }],
      },
    ],
    selectedOptionId: 'A',
    citation:
      'Gilbert, S., & Lynch, N. (2002). "Brewer\'s Conjecture and the Feasibility of Consistent, Available, Partition-Tolerant Web Services." ACM SIGACT News.',
  },
  {
    number: 3,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 1.5,
    prompt: [
      { value: 'A ' },
      { value: 'TCP', code: true },
      { value: ' connection establishment uses a three-way handshake. Which sequence of flags correctly describes the handshake from the client\'s perspective?' },
    ],
    specTitle: 'FORMAL STATE SPECIFICATION (§3-WAY HANDSHAKE)',
    specLink: 'RFC 793 Transmission Control Protocol',
    specLines: [
      '[Client: CLOSED]        [Server: LISTEN]',
      '  |  --- SYN --->            |',
      '  |  <--- SYN,ACK ---        |',
      '  |  --- ACK --->            |',
      '[Client: ESTABLISHED]   [Server: ESTABLISHED]',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'Client sends ' },
          { value: 'SYN', code: true },
          { value: ', server responds with ' },
          { value: 'SYN, ACK', code: true },
          { value: ', client responds with ' },
          { value: 'ACK', code: true },
          { value: ', completing the handshake.' },
        ],
      },
      {
        id: 'B',
        text: [
          { value: 'Client sends ' },
          { value: 'ACK', code: true },
          { value: ', server responds with ' },
          { value: 'SYN', code: true },
          { value: ', client responds with ' },
          { value: 'FIN', code: true },
          { value: '.' },
        ],
      },
      {
        id: 'C',
        text: [{ value: 'Client and server exchange ' }, { value: 'SYN', code: true }, { value: ' packets simultaneously with no acknowledgment required.' }],
      },
      {
        id: 'D',
        text: [
          { value: 'The handshake requires four messages: ' },
          { value: 'SYN', code: true },
          { value: ', ' },
          { value: 'ACK', code: true },
          { value: ', ' },
          { value: 'SYN', code: true },
          { value: ', ' },
          { value: 'FIN', code: true },
          { value: '.' },
        ],
      },
    ],
    selectedOptionId: null,
    citation: 'Postel, J. (1981). "Transmission Control Protocol." RFC 793, Section 3.4.',
  },
  {
    number: 4,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 2.0,
    prompt: [
      { value: 'Consistent hashing is commonly used to distribute keys across nodes in a distributed cache (e.g. ' },
      { value: 'Dynamo', code: true },
      { value: '-style systems). What is the primary advantage of consistent hashing over simple modulo hashing (' },
      { value: 'hash(key) % N', code: true },
      { value: ') when the number of nodes ' },
      { value: 'N', code: true },
      { value: ' changes?' },
    ],
    specTitle: 'FORMAL PROPERTY (§4.1 REBALANCING COST)',
    specLink: 'Consistent Hashing and Random Trees',
    specLines: [
      '[Ring: 0 .. 2^m - 1]',
      '  nodes placed at hash(node_id) positions',
      '  key -> assigned to first node clockwise from hash(key)',
      '  on node add/remove: only O(K/N) keys remap, not all keys',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'It minimizes the number of keys that must be remapped, moving on average only ' },
          { value: 'K/N', code: true },
          { value: ' keys instead of nearly all keys.' },
        ],
      },
      {
        id: 'B',
        text: [{ value: 'It guarantees perfectly equal load distribution across all nodes with zero variance, regardless of node count.' }],
      },
      {
        id: 'C',
        text: [{ value: 'It eliminates the need for replication since each key maps to exactly one permanent node forever.' }],
      },
      {
        id: 'D',
        text: [
          { value: 'It reduces hash computation time from ' },
          { value: 'O(log n)', code: true },
          { value: ' to ' },
          { value: 'O(1)', code: true },
          { value: ' for every lookup.' },
        ],
      },
    ],
    selectedOptionId: null,
    citation: 'Karger, D. et al. (1997). "Consistent Hashing and Random Trees." ACM STOC \'97.',
  },
  {
    number: 5,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 1.5,
    prompt: [
      { value: 'The ' },
      { value: 'ACID', code: true },
      { value: ' properties describe guarantees provided by traditional relational database transactions. Which option correctly pairs each letter with its property?' },
    ],
    specTitle: 'FORMAL DEFINITION (§2.3 TRANSACTION GUARANTEES)',
    specLink: 'Database Transaction Model',
    specLines: [
      'A - Atomicity   : all-or-nothing execution',
      'C - Consistency : valid state -> valid state',
      'I - Isolation   : concurrent txns appear serial',
      'D - Durability  : committed data survives crashes',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'Atomicity (all-or-nothing), Consistency (valid state transitions), Isolation (concurrent transactions appear serial), Durability (committed data survives crashes).' },
        ],
      },
      { id: 'B', text: [{ value: 'Availability, Concurrency, Idempotency, Determinism — four independent scheduling guarantees.' }] },
      { id: 'C', text: [{ value: 'Atomicity refers only to disk writes, while the other three letters describe network-layer guarantees.' }] },
      { id: 'D', text: [{ value: 'ACID is an acronym exclusive to NoSQL document stores and does not apply to relational databases.' }] },
    ],
    selectedOptionId: 'A',
    citation: 'Haerder, T., & Reuter, A. (1983). "Principles of Transaction-Oriented Database Recovery." ACM Computing Surveys.',
  },
  {
    number: 6,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 1.5,
    prompt: [
      { value: 'What is the worst-case time complexity of searching for a key in a balanced binary search tree (e.g. an ' },
      { value: 'AVL', code: true },
      { value: ' or ' },
      { value: 'Red-Black', code: true },
      { value: ' tree) containing ' },
      { value: 'n', code: true },
      { value: ' elements?' },
    ],
    specTitle: 'FORMAL BOUND (§BALANCED BST HEIGHT)',
    specLink: 'Balanced Tree Height Invariant',
    specLines: [
      '[Invariant: height h = O(log n) for balanced BST]',
      '  search cost <= h comparisons',
      '  => worst-case search = O(log n)',
    ],
    options: [
      { id: 'A', text: [{ value: 'O(log n), because balancing keeps the tree height proportional to the logarithm of the number of nodes.' }] },
      { id: 'B', text: [{ value: 'O(n), the same as searching an unsorted linked list.' }] },
      { id: 'C', text: [{ value: 'O(1), because binary search trees use direct index access like arrays.' }] },
      { id: 'D', text: [{ value: 'O(n log n), matching the cost of comparison-based sorting algorithms.' }] },
    ],
    selectedOptionId: 'A',
    citation: 'Cormen, T. H. et al. (2009). "Introduction to Algorithms," 3rd ed., Chapter 13.',
  },
  {
    number: 7,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 2.0,
    prompt: [
      { value: 'In a preemptive priority-based CPU scheduler, what problem can occur when a high-priority process is repeatedly favored over a low-priority process, and what is the standard mitigation technique?' },
    ],
    specTitle: 'FORMAL DEFINITION (§SCHEDULER FAIRNESS)',
    specLink: 'OS Scheduling: Priority Inversion & Starvation',
    specLines: [
      '[Problem: Starvation]',
      '  low-priority process never scheduled while',
      '  higher-priority processes keep arriving',
      '[Mitigation: Aging]',
      '  priority(p) increases the longer p waits in the ready queue',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'This causes ' },
          { value: 'starvation', code: true },
          { value: ' of the low-priority process; the standard mitigation is ' },
          { value: 'aging', code: true },
          { value: ', gradually increasing its priority the longer it waits.' },
        ],
      },
      { id: 'B', text: [{ value: 'This causes a deadlock, mitigated by rolling back both processes to their initial state.' }] },
      { id: 'C', text: [{ value: 'This causes thrashing, mitigated by increasing the size of physical RAM.' }] },
      { id: 'D', text: [{ value: 'This is expected behavior and requires no mitigation in any scheduling policy.' }] },
    ],
    selectedOptionId: null,
    citation: 'Silberschatz, A. et al. (2018). "Operating System Concepts," 10th ed., Chapter 5.',
  },
  {
    number: 8,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 1.5,
    prompt: [
      { value: 'In public-key (asymmetric) cryptography such as ' },
      { value: 'RSA', code: true },
      { value: ', which statement correctly describes how encryption and digital signatures use the key pair?' },
    ],
    specTitle: 'FORMAL USAGE (§ASYMMETRIC KEY OPERATIONS)',
    specLink: 'Public-Key Cryptography Primer',
    specLines: [
      '[Encryption]  sender uses recipient PUBLIC key -> only recipient PRIVATE key decrypts',
      '[Signature]   signer uses own PRIVATE key -> anyone verifies with signer PUBLIC key',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'To encrypt a message for someone, you use their ' },
          { value: 'public key', code: true },
          { value: '; to sign a message yourself, you use your own ' },
          { value: 'private key', code: true },
          { value: '.' },
        ],
      },
      { id: 'B', text: [{ value: 'Both encryption and signing always use the sender\'s private key exclusively.' }] },
      { id: 'C', text: [{ value: 'Public and private keys are interchangeable and either may be used for any operation.' }] },
      { id: 'D', text: [{ value: 'Digital signatures require a shared symmetric key exchanged in advance over a secure channel.' }] },
    ],
    selectedOptionId: null,
    citation: 'Rivest, R., Shamir, A., & Adleman, L. (1978). "A Method for Obtaining Digital Signatures and Public-Key Cryptosystems." CACM.',
  },
  {
    number: 9,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 1.5,
    prompt: [
      { value: 'At which layer of the ' },
      { value: 'OSI', code: true },
      { value: ' model does a network switch primarily operate when forwarding frames based on ' },
      { value: 'MAC address', code: true },
      { value: '?' },
    ],
    specTitle: 'FORMAL MAPPING (§OSI LAYER RESPONSIBILITIES)',
    specLink: 'OSI Seven-Layer Reference Model',
    specLines: [
      'L1 Physical    - bits on the wire',
      'L2 Data Link   - MAC addressing, frames, switches',
      'L3 Network     - IP addressing, routing, routers',
      'L4 Transport   - TCP/UDP, ports',
    ],
    options: [
      { id: 'A', text: [{ value: 'Layer 2 (Data Link), since switches forward Ethernet frames using MAC address tables.' }] },
      { id: 'B', text: [{ value: 'Layer 3 (Network), since switches route packets based on IP addresses.' }] },
      { id: 'C', text: [{ value: 'Layer 4 (Transport), since switches inspect TCP port numbers to forward traffic.' }] },
      { id: 'D', text: [{ value: 'Layer 7 (Application), since modern switches decode HTTP headers directly.' }] },
    ],
    selectedOptionId: null,
    citation: 'Tanenbaum, A. S., & Wetherall, D. (2011). "Computer Networks," 5th ed., Chapter 1.',
  },
  {
    number: 10,
    totalQuestions: 10,
    type: 'Single Choice',
    points: 2.0,
    prompt: [
      { value: 'A composite ' },
      { value: 'B+ tree', code: true },
      { value: ' index is created on columns ' },
      { value: '(last_name, first_name)', code: true },
      { value: ' of a table. Following the leftmost-prefix rule, which query below can ' },
      { value: 'fully', code: true },
      { value: ' use this index for its ' },
      { value: 'WHERE', code: true },
      { value: ' clause lookup?' },
    ],
    specTitle: 'FORMAL RULE (§LEFTMOST PREFIX INDEXING)',
    specLink: 'B+ Tree Composite Index Semantics',
    specLines: [
      '[Index key order: (last_name, first_name)]',
      '  usable prefixes: (last_name), (last_name, first_name)',
      '  NOT directly usable: (first_name) alone',
    ],
    options: [
      {
        id: 'A',
        text: [
          { value: 'WHERE last_name = ' },
          { value: "'Vance'", code: true },
          { value: ' AND first_name = ' },
          { value: "'Eli'", code: true },
          { value: ' — the predicate matches the full composite key in order.' },
        ],
      },
      {
        id: 'B',
        text: [
          { value: 'WHERE first_name = ' },
          { value: "'Eli'", code: true },
          { value: ' — filtering only on the second column of the composite key.' },
        ],
      },
      {
        id: 'C',
        text: [{ value: 'WHERE UPPER(last_name) = ' }, { value: "'VANCE'", code: true }, { value: ' — wrapping the leading column in a function.' }],
      },
      {
        id: 'D',
        text: [{ value: 'Any query on this table automatically uses the index regardless of which columns appear in the WHERE clause.' }],
      },
    ],
    selectedOptionId: null,
    citation: 'Petkovic, D. (2020). "Database Indexing for Beginners." Relational Index Design Notes, Chapter 4.',
  },
];

export const navigatorState: NavigatorState = {
  totalQuestions: 10,
  current: 1,
  answeredCount: 4,
  flaggedCount: 2,
  unansweredCount: 6,
  flaggedIds: [4, 8],
  nextUnanswered: 3,
  answeredIds: [1, 2, 5, 6],
};