import type { HistogramBucket, StudentRow, StatsData } from './types';

export const stats: StatsData = {
  submissionRate: { percent: 92.2, submitted: 118, total: 128 },
  averageScore: { value: 8.6, max: 10, min: 4.0, median: 8.8 },
  averageTime: { value: '32m 10s', fastest: '18 phút', slowest: '58 phút' },
  hardestQuestion: {
    label: 'Câu 14: Election timeout...',
    correctRate: 38,
    link: 'Xem phân tích câu hỏi',
  },
};

export const histogram: HistogramBucket[] = [
  { range: '< 5.0', count: 3, colorKey: 'danger' },
  { range: '5.0 - 6.9', count: 9, colorKey: 'histpink' },
  { range: '7.0 - 7.9', count: 26, colorKey: 'histlav' },
  { range: '8.0 - 8.9', count: 48, colorKey: 'brand' },
  { range: '9.0 - 10.0', count: 32, colorKey: 'success' },
];

export const students: StudentRow[] = [
  {
    id: 'MSSV: 20521234',
    name: 'Trần Minh Quân',
    submittedAt: '02:12:14 - 24/10/2025',
    duration: '21 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 10.0,
    integrityScore: 10,
    integrityBadge: { label: 'Hoàn thành đúng', tone: 'success' },
    lecturerAction: 'Nhấn để chỉnh sửa',
  },
  {
    id: 'MSSV: 20521099',
    name: 'Nguyễn Thùy Linh',
    submittedAt: '14:08:32 - 24/10/2025',
    duration: '27 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 9.6,
    integrityScore: 10,
    integrityBadge: { label: 'Hoàn thành đúng', tone: 'success' },
    lecturerAction: 'Nhấn để chỉnh sửa',
  },
  {
    id: 'MSSV: 20521187',
    name: 'Lê Hoàng Nam',
    submittedAt: '19:47:18 - 24/10/2025',
    duration: '32 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 8.4,
    integrityScore: 10,
    integrityBadge: { label: 'Hoàn thành đúng', tone: 'success' },
    lecturerAction: 'Nhấn để chỉnh sửa',
  },
  {
    id: 'MSSV: 20521345',
    name: 'Đỗ Quốc Tuấn',
    submittedAt: '11:24:50 - 24/10/2025',
    duration: '15 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 7.2,
    integrityScore: 13,
    integrityBadge: { label: 'Chuyển bài trễ', tone: 'warn' },
    lecturerAction: 'Chấm lại bài (Mất phiên bản)',
  },
  {
    id: 'MSSV: 20521278',
    name: 'Phạm Mai Hương',
    submittedAt: '16:19:36 - 24/10/2025',
    duration: '29 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 9.2,
    integrityScore: 10,
    integrityBadge: { label: 'Hoàn thành đúng', tone: 'success' },
    lecturerAction: 'Nhấn để chỉnh sửa',
  },
  {
    id: 'MSSV: 20521410',
    name: 'Vũ Đức Huy',
    submittedAt: 'Chưa nộp bài',
    duration: '—',
    attemptsNote: 'Attempt: 0',
    autoScore: null,
    integrityScore: null,
    integrityBadge: { label: 'Đang xử lý', tone: 'neutral' },
    lecturerAction: 'Gửi nhắc nhở',
  },
  {
    id: 'MSSV: 20521156',
    name: 'Đặng Thu Trang',
    submittedAt: '20:03:44 - 24/10/2025',
    duration: '26 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 8.9,
    integrityScore: 10,
    integrityBadge: { label: 'Hoàn thành đúng', tone: 'success' },
    lecturerAction: 'Nhấn để chỉnh sửa',
  },
  {
    id: 'MSSV: 20521302',
    name: 'Hoàng Gia Bách',
    submittedAt: '22:15:21 - 24/10/2025',
    duration: '35 phút',
    attemptsNote: 'Attempt: 1',
    autoScore: 4.8,
    integrityScore: 13,
    integrityBadge: { label: 'Không đạt log', tone: 'danger' },
    lecturerAction: 'Chấm lại bài (Mất phiên bản)',
  },
];
