server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/enrollment_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:ptandat66}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=${JWT_SECRET:DayLaMotSecretKeyRatDaiVaDuBaoMatChoViecTestRole123!}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=INFO

# Application Info
spring.application.name=enrollment-service

# Actuator Health Check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=when-authorized
