server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: academic-service
          uri: lb://ACADEMIC-SERVICE
          predicates:
            - Path=/api/academic/**
          filters:
            - RewritePath=/api/academic/(?<segment>.*), /api/${segment}

        - id: activity-service
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activity/**
          filters:
            - RewritePath=/api/activity/(?<segment>.*), /api/${segment}

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info
